services:
  taskflow-api:
    build: .
    container_name: taskflow_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskflow
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: taskflow_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
